# Generated by Django 5.2.4 on 2025-08-12 08:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='images\\default.png', null=True, upload_to=account.models.user_directory_path),
        ),
    ]
