# Generated by Django 5.2.4 on 2025-08-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='millage',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
