# Generated by Django 5.2.4 on 2025-08-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_quotationrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='service_requested',
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='service_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.services'),
        ),
    ]
