# Generated by Django 5.2.4 on 2025-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_quotationrequest_transmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='gas',
            field=models.CharField(blank=True, choices=[('petro', 'Petrol'), ('diesel', 'diesil')], max_length=10, null=True),
        ),
    ]
