# Generated by Django 5.2.4 on 2025-08-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_quotationrequest_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='gas',
            field=models.CharField(blank=True, choices=[('petro', 'Petrol'), ('diesel', 'diesel')], max_length=10, null=True),
        ),
    ]
