# Generated by Django 5.2.4 on 2025-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_quotationrequest_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
