# Generated by Django 5.2.4 on 2025-09-02 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_booking_quotation_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['time_slot'], name='service_boo_time_sl_406c02_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['quotation'], name='service_boo_quotati_8e7c11_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='service_boo_user_id_f55e46_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('quotation',), name='unique_quotation_booking'),
        ),
    ]
