# Generated by Django 5.2.4 on 2025-09-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_timeslot_date_booking_service_boo_time_sl_406c02_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
