# Generated by Django 5.2.4 on 2025-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
